############## Iron Acquisition Potential of Mosquito Associated Bacteria #############
        # Author: Aidan Foo 
        # Email 248064@lstmed.ac.uk 
        # Version: 0.1 
#######################################################################################


import pandas as pd

configfile: "../config/config.yaml"

sample_table = (
    pd.read_csv(config["samples"], sep = "\t", dtype = {"sampleID": str})
    .set_index(["sampleID"], drop = False)
    .sort_index()
)

samples = sample_table["sampleID"].tolist()

include: "rules/01_QC.smk"
include: "rules/02_Assembly.smk"
include: "rules/03_TaxonomicClassification.smk"
include: "rules/04_Genome_Classification_GTDB.smk"
include: "rules/05_fegenie.smk"
include: "rules/06_BGC_search.smk"
include: "rules/PipelineFunction.smk"

rule all:
    """
        Run the Pipeline
    """
    input:
        RunPipeLine